### ISSUE TITLE
Console does not list response examples when response type has examples but there are also examples defined at response level

### ISSUE THREAD

**Issue by carobazan** [advanced-rest-client/api-console-app#1]
### Description
When a resource has a response defined of a type containing examples and the response also has examples defined, Api console is listing examples defined in type instead of showing the examples defined for response

### Expected outcome
When API Console describes the resource, it should show the response examples as defined in response

### Actual outcome
When API Console describes the resource, it shows the examples defined in response type

### Steps to reproduce
1. Having the api in the attached [testExamples.zip](https://github.com/advanced-rest-client/api-console-app/files/910912/testExamples.zip) deployed as public (I used API Manager and Portal) 
2. Open new Api Console and load the api url
3. Click on resource with name starting as CASE3_
4. Click on Examples tab

response is defined as 
```  
  responses: 
      200: 
        body: 
          application/json: 
            type: myTypes.LibObjectWithExamples
            examples:
              example1: 
                ok: true
                channel: 
                  id: "ex1"
                  owner: "A"
              example2: 
                ok: false
                channel: 
                  id: "ex2"
                  owner: "B"
```
Nevertheless console shows the examples defined in the response type: myTypes.LibObjectWithExamples

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jarrodek** [comment]
The problem was with `raml2object` community library. It was overwritten response's `examples` array with type's. This was corrected and now the `raml-json-enhancer` will use new version of the library with corrected algorithm.

To test it again, please, use `bower update` command to update elements.
