### ISSUE TITLE
try it should not be supported for Custom security types

### ISSUE THREAD

**Issue by carobazan** [advanced-rest-client/api-console-app#6]
### Description
When a resource has a custom security type, "Try it" should no be permitted, instead new console allows to perform try it and then an error 400 is shown

### Expected outcome
A message should prevent user from using try it:
Custom Security Schemes are not supported in Try It

### Actual outcome
404 error when using try it

### Steps to reproduce
1. Having an api with a resource set with custom security type (example /testSecuredByCustomAuth in attached api, [testSecurity.zip](https://github.com/advanced-rest-client/api-console-app/files/925716/testSecurity.zip))
2. Open in new console and select the resource get operation
3. click on Try it

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jarrodek** [comment]
The issue is quite opposite :)
The console should allow custom security schemes. This is a pending feature request.

**Comment by jarrodek** [comment]
The console will now support custom security schemes.

Please, `bower update` components to test again.
