### ISSUE TITLE
When using security scheme type Digest, "Try it" should not be supported

### ISSUE THREAD

**Issue by carobazan** [advanced-rest-client/api-console-app#9]
### Description
Using security type Digest : "try it" should show a message like "Custom Security Schemes are not supported in Try It". 

### Steps to reproduce
1. Define a resource using a security scheme of Digest type:
```
  digest:
    type: Digest Authentication
    description: Testing digets security
    describedBy: 
      queryParameters: 
        id: string
      responses: 
        200:
          body: 
            application/json:
              type: string
              example: DELETED
```

2. use the scheme in one of the resources, then open in console :
3. Click Try it
a message should prevent users from trying it 

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by jarrodek** [comment]
I see no reason why.

If the request (transport) is handled by the browser then internal browser implementation will handle digest authentication. Though, it will ask the user to provide username and password again.

If the user use advanced options in digest form it will generate correct authorization header.

Also, the console allows to define custom transport method and it require to get authorization data from the user to perform the query.

So it is working as intended.
